<ips:template parameters="" />
{{if theme.slider_5}}
	{{if theme.slider_5_wcs =='*' or \IPS\Member::loggedIn()->inGroup( explode( ',', theme.slider_5_wcs ) )}}
		<div class="swiper-slide slide-Custom-5">
			{{if theme.slider_lazyloading}}<div class="Ta_lazyPreloader"><span></span><span></span><span></span></div>{{endif}}
			<div class="swiper-lazy slide-bg" {{if theme.slider_5_img}}{{if theme.slider_lazyloading}}data-background="{theme="slider_5_img"}"{{else}}style="background-image: url({theme="slider_5_img"});"{{endif}}{{endif}}></div>
			{{if theme.slider_enable_overlay || theme.slider_enablecoloroverlay}}<div class="slide-overlay"></div>{{endif}}
			{{if theme.slider_5_content || theme.slider_5_title || theme.slider_5_buttons}}
				<div class="slide-contents" {{if (in_array(theme.slider_effect, array('slide', 'fade')))}}data-swiper-parallax="-100%"{{endif}}>
			  		<h4 class="ipsType_veryLarge" {{if (in_array(theme.slider_effect, array('slide', 'fade')))}}data-swiper-parallax="-55%"{{endif}}><span>{theme="slider_5_title"}</span></h4>
			  		<section class='ipsType_normal ipsType_richText ipsType_break'>{theme="slider_5_content"}</section>
					{theme="slider_5_buttons"}
				</div>
          	{{endif}}
		</div>
	{{endif}}
{{endif}}
