<?php

$lang = array(
'themesetting_g_widget_content_color'		=> 'Widget content color',
'themesetting_slider_1_img'		=> 'Slider Image',
'themesetting_slider_1_buttons'		=> 'Slider Buttons',
'themesetting_social_locationt'		=> 'Show on top',
'ta_themes_menu_more'		=> 'MORE',
'themesetting_pagination_fontcolor'		=> 'Pagination: Text',
'themesetting_editor_toolbarbg'		=> 'Editor Toolbar Background',
'themesetting_search_font_color'		=> 'Search Typing Font',
'themesetting_search_background'		=> 'Search background',
'themesetting_cat_private_r3'		=> 'Apply a cover (3)',
'themesetting_tabs_buttonbg'		=> 'Tabs: Button background',
'themesetting_search_icon'		=> 'Search icon Color',
'themesetting_ipsmenu_bghover'		=> 'ipsMenu background hover',
'themesetting_dataitem_status'		=> 'Data item background: Status',
'themesetting_messages_warning'		=> 'Message background: Warning',
'themesetting_header_position'		=> 'User Bar & Nav Bar type',
'themesetting_dataitem_warning'		=> 'Data item background: Warning',
'themesetting_slider_reorder'		=> 'Slider sorting',
'themesetting_widget_title_bar_border'		=> 'Widget Title Bar: Border',
'themesetting_header_remob'		=> 'Header image: Remove on mobile',
'themesetting_dataitem_new_success'		=> 'Data item background: New & Suscess',
'themesetting_topic_unread_border'		=> 'Topic Unread Separator border',
'themesetting_section_title_bar_border'		=> 'Section Title Bar: Border',
'themesetting_slider_3_wcs'		=> 'Who can see?',
'themesetting_cat_private_g_r2'		=> 'Exclude from (2)',
'themesetting_sidebar_width'		=> 'Sidebar width (in px)',
'themesetting_pagination_actifont'		=> 'Pagination: Active text',
'themesetting_ipsmenu_title_color'		=> 'ipsMenu Title Font Color',
'themesetting_ipsmenu_fonthover'		=> 'ipsMenu font hover',
'themesetting_slider_3_title'		=> 'Title',
'themesetting_dataitem_zebra'		=> 'Data item background: Zebra',
'themesetting_cat_private_bg_r1'		=> 'Cover background (1)<span id="themesettings_desc">%70 Transparent</span>',
'themesetting_slider_2_wcs'		=> 'Who can see?',
'themesetting_sl_background'		=> 'Background',
'themesetting_input_focusbg'		=> 'Input: Focus background',
'themesetting_sl_icon_bgcolor'		=> 'Icon: Background color',
'themesetting_ipsquote_fontclr'		=> 'Quote header font color',
'themesetting_slider_wheretoshow'		=> 'Where to show?',
'themesetting_slider_2_img'		=> 'Slider Image',
'themesetting_messages_font'		=> 'Messages: Text color',
'themesetting_slider_5_img'		=> 'Slider Image',
'themesetting_userbar_bg'		=> 'User Bar Background',
'themesetting_cat_private_ti_r1'		=> 'Cover title (1)',
'themesetting_header_borders'		=> 'Header border seperators<span id="themesettings_desc">Border colors between userBar and navBar</span>',
'themesetting_input_focusborder'		=> 'Input: Focus border',
'themesetting_cat_private_bg_r2'		=> 'Cover background (2)<span id="themesettings_desc">%70 Transparent</span>',
'themesetting_widget_titbar_custcss'		=> 'Widget Title Bar Custom CSS',
'themesetting_category_r3'		=> 'Style forum categories (3)',
'theme_custom_tab_swiper_slider'		=> 'Swiper Slider',
'themesetting_slider_enablecoloroverlay'		=> 'Enable Color overlay',
'themesetting_slider_article_icon'		=> 'Article icons color',
'themesetting_input_bordercolor'		=> 'Input: Border color',
'themesetting_slider_coloroverlay'		=> 'Color overlay',
'themesetting_footer_text'		=> 'Copyright Footer: Links',
'themesetting_pagination_active'		=> 'Pagination: Active background',
'themesetting_cat_id_r1'		=> 'Category<span id="themesettings_desc">Multiple choice available</span>',
'themesetting_social_links_hide'		=> 'Hide in Header & Footer',
'themesetting_headerimage_height'		=> 'Header image: Height (in px)<span id="themesettings_desc">Minimum height: 120. Maximum height: 500</span>',
'themesetting_notification_unreadbg'		=> 'Notification: New status background',
'theme_custom_tab_header'		=> 'Header & Menus',
'themesetting_checkbox_no'		=> 'Checkboxes: No background',
'themesetting_checkbox_yes'		=> 'Checkboxes: Yes background',
'themesetting_checkbox_icon'		=> 'Checkboxes: Icon color',
'themesetting_tabs_activebutton'		=> 'Tabs: Active button background',
'themesetting_navbar_toggleNav'		=> 'Toggle navbar panel',
'themesetting_nt_pages_content'		=> 'Pages Articles',
'themesetting_headerimage_hidemobile'		=> 'Header image: Hide on mobile',
'themesetting_slider_enable_autoplay'		=> 'Autoplay',
'themesetting_ipsbox_bg'		=> 'ipsBox background',
'themesetting_navbar_position'		=> 'Navbar position',
'themesetting_ipsbox_border'		=> 'ipsBox border',
'themesetting_slider_effect'		=> 'Sliding Effect',
'themesetting_g_widget_position_top'		=> 'Where to show?',
'themesetting_input_bg'		=> 'Input: Background',
'themesetting_footer_borders'		=> 'Borders color',
'themesetting_g_widget_background'		=> 'Widget Background',
'themesetting_progressbar_bg'		=> 'Progres Bar background',
'themesetting_mentions'		=> 'Mentions: Background color',
'themesetting_header_layout'		=> 'Header & Slider & Footer Layout',
'themesetting_footer_quicklinks'		=> 'Quick links',
'themesetting_slider_1_content'		=> 'Content',
'themesetting_footer_headercolor'		=> 'Header Font Color',
'themesetting_topic_author_panel_width'		=> 'Topic Author panel Width (in px)',
'themesetting_mentions_font'		=> 'Mentions: Text color',
'themesetting_widget_bg'		=> 'Widget background<span id="themesettings_desc">A Background used on all widgets</span>',
'themesetting_menu_borders'		=> 'Secondary Nav Bar border<span id="themesettings_desc">1px Solid border surounded on secondary menu</span>',
'themesetting_repscore_positivecol'		=> 'Profile: Positive reputation color',
'themesetting_nt_title_bg'		=> 'Title background',
'themesetting_g_widget_title_top'		=> 'Title',
'themesetting_slider_navigation_buttons'		=> 'Show navigation',
'themesetting_repscore_positivebg'		=> 'Profile: Positive reputation background',
'themesetting_footer_backgroundimage_opacity'		=> 'Image Opacity',
'themesetting_slider_1_wcs'		=> 'Who can see?',
'themesetting_slider_2_title'		=> 'Title',
'themesetting_enable_widget_bottom'		=> 'Bottom Widget',
'themesetting_nt_whocansee'		=> 'Who can see?',
'themesetting_slider_loop'		=> 'Loop mode',
'themesetting_slider_height'		=> 'Slider Height (in px)',
'themesetting_slider_3_content'		=> 'Content',
'themesetting_slider_4_title'		=> 'Title',
'themesetting_body_fontcustom'		=> 'Body Font: Custom<span id="themesettings_desc">Type a<a href="https://fonts.google.com/" target="_blank" id="themesettings_desc_a">google fonts</a>name</span>',
'themesetting_footer_bgimage'		=> 'Background Image',
'themesetting_footer_fonthovers'		=> 'Hover colors',
'themesetting_custom_editorstyle'		=> 'Change EDITOR colors<span id="themesettings_desc">Disable if you want to use the default skin colors, or installing a new skin :).',
'themesetting_widget_borders'		=> 'Widget Border',
'themesetting_cat_private_ti_font_r3'		=> 'Cover title color (3)',
'themesetting_slider_3'		=> 'Slider (3)',
'themesetting_g_whocansee_bottom'		=> 'Who can see?',
'themesetting_nav_active_tab'		=> 'Main Nav Bar active tab Background',
'themesetting_widget_bg_y'		=> 'Widget background gradient',
'themesetting_cat_ti_bg_gradi_r3'		=> 'Category title gradients (3)<span id="themesettings_desc">Some gradient websites<a href="http://www.colorzilla.com/gradient-editor/" target="_blank" id="themesettings_desc_a"> gradient-editor </a><a href="http://uigradients.com/" target="_blank" id="themesettings_desc_a"> uigradients </a></span>',
'themesetting_slider_1'		=> 'Slider (1)',
'themesetting_topic_author_panel'		=> 'Author panel background',
'themesetting_enable_slider'		=> 'Slider On/Off',
'theme_custom_tab_swiper_sliders'		=> 'Sliders',
'themesetting_dialogbg'		=> 'Pop-up: Backgrounds',
'themesetting_notification_readfont'		=> 'Notification: Status font',
'themesetting_userbar_style'		=> 'Userbar style',
'themesetting_enable_widget_top'		=> 'Top Widget',
'themesetting_react_bg'		=> 'Reactions background',
'themesetting_cat_private_g_r1'		=> 'Exclude from (1)',
'themesetting_cat_ti_bg_r2'		=> 'Category title background (2)',
'themesetting_slider_4_wcs'		=> 'Who can see?',
'themesetting_header_imgposition'		=> 'Header background position',
'themesetting_slider_content_title_fontsize'		=> 'Content Title Font Size (in px)',
'themesetting_slider_content_title_font'		=> 'Content Title Font Color',
'themesetting_slider_2'		=> 'Slider (2)',
'themesetting_cat_private_g_r3'		=> 'Exclude from (3)',
'themesetting_slider_content_background'		=> 'Content custom CSS',
'theme_custom_tab_forms_toggles'		=> 'Forms & Toggles',
'themesetting_editor_tlbartabhover'		=> 'Editor Toolbar tabs Hover',
'themesetting_forum_list_border'		=> 'Forum list Border color',
'themesettings_slider_lazyloading'		=> 'Lazy Loading<span id="themesettings_desc">enable/disable lazy laoding of slider images.</span>',
'themesetting_messages_general'		=> 'Message background: General',
'themesetting_tabs_actifocolor'		=> 'Tabs: Active button text',
'themesetting_slider_enable_pagination'		=> 'Show pagenition',
'themesetting_truncate_about'		=> 'Truncate "About us"<span id="themesettings_desc">Enable to manage how many lines to show in About Us and the reast to be in a "Readmore" button</span>',
'themesetting_slider_image_position'		=> 'Slider image positions<span id="themesettings_desc">This field sets the starting position of slider images, You can use one of the follwing keywords or values in percentage and pixels.</span><span id="themesettings_desc"><em><strong>left top, left center, left bottom, right top, right center, right bottom, center top, center center, center bottom</strong></em></span>',
'themesetting_editor_comareabor'		=> 'Editor Compose Area Border',
'themesetting_section_title_gradients'		=> 'Section title bar custom CSS',
'themesetting_cat_private_r2'		=> 'Apply a cover (2)',
'themesetting_slider_1_title'		=> 'Title',
'themesetting_footer_fontcolor'		=> 'Font Color',
'themesetting_body_bg_gradients'		=> 'Body: Background gradients<span id="themesettings_desc">Some gradient websites<a href="http://www.colorzilla.com/gradient-editor/" target="_blank" id="themesettings_desc_a"> gradient-editor </a><a href="http://uigradients.com/" target="_blank" id="themesettings_desc_a"> uigradients </a></span>',
'themesetting_navbaruserbar_opacity'		=> 'Navbar & Userbar Opacity',
'themesettings_slider_swiping'		=> 'Swiping mode<span id="themesettings_desc">enable/disable swiping mode</span>',
'themesetting_nt_background'		=> 'Background',
'themesetting_repscore_negativecol'		=> 'Profile: Negative reputation color',
'themesetting_cat_id_r2'		=> 'Category<span id="themesettings_desc">Multiple choice available</span>',
'themesetting_flashmessage_font'		=> 'Flash Message: Text color',
'themesetting_selecttree_border'		=> 'SelectTree: Border',
'themesetting_slider_2_content'		=> 'Content',
'themesetting_sl_bordercolor'		=> 'Border color',
'themesetting_ipsquote_hdr'		=> 'Quote Header background',
'themesetting_cat_id_r3'		=> 'Category<span id="themesettings_desc">Multiple choice available</span>',
'themesetting_enable_slider_whocansee'		=> 'Who can see?',
'themesetting_cat_private_ti_font_r1'		=> 'Cover title color (1)',
'themesetting_tab_panelbg'		=> 'Tabs: Panel background',
'themesetting_main_nav_fontsize'		=> 'Main Nav Bar: Font size (in px)',
'themesetting_sl_iconhovercolor'		=> 'Background: Hover color',
'themesetting_footer_toggle'		=> 'Enable Extra footer',
'themesetting_main_nav_font_hover'		=> 'Main Nav Bar Font Hover',
'themesetting_widget_title_bar'		=> 'Widget Title Bar background',
'themesetting_main_nav_tab_bg_hover'		=> 'Secondary Nav Bar background hover',
'themesetting_cat_private_ti_font_r2'		=> 'Cover title color (2)',
'themesetting_header_imageheight'		=> 'Header height (in px)',
'themesetting_main_nav_tab'		=> 'Secondary Nav Bar background',
'themesetting_slider_exclude'		=> 'Exclude on',
'themesetting_main_nav_bg'		=> 'Main Nav bar background',
'themesetting_slider_3_buttons'		=> 'Slider Buttons',
'themesetting_main_nav_bg_hover'		=> 'Main Nav Bar background hover',
'themesetting_footer_aboutheader'		=> 'About us header',
'themesetting_editor_areabg'		=> 'Editor Area Background',
'themesetting_topic_background'		=> 'Topic background',
'themesetting_nt_tickers'		=> 'Tickers',
'themesetting_category_r2'		=> 'Style forum categories (2)',
'themesetting_input_font'		=> 'Input: Text color',
'themesetting_nt_fontcolor'		=> 'Font color',
'themesetting_userbar_font_color'		=> 'User Bar Font Color',
'themesetting_footer_background'		=> 'Background',
'theme_custom_tab_footer'		=> 'Footer',
'themesetting_main_nav_tab_font_hover'		=> 'Secondary Nav Bar font hover',
'themesetting_footer_about'		=> 'About us',
'themesetting_truncate_lines'		=> 'Truncate lines',
'themesetting_cat_ti_bg_r3'		=> 'Category title background (3)',
'theme_custom_tab_forum_categories'		=> 'Style forums',
'themesetting_slider_overlay'		=> 'Texture',
'themesetting_nt_speed'		=> 'Speed',
'themesetting_repscore_negativebg'		=> 'Profile: Negative reputation Background',
'themesetting_cat_ti_font_r1'		=> 'Category title color (1)',
'themesetting_g_widget_title_bottom'		=> 'Title',
'themesetting_g_whocansee_top'		=> 'Who can see?',
'theme_custom_tab_news_ticker'		=> 'News Ticker',
'themesetting_slider_overlayopacity'		=> 'Texture Overlay: Opacity',
'themesetting_nt_title_color'		=> 'Title font color',
'themesetting_slider_enable_overlay'		=> 'Enable Texture overlay',
'themesetting_repscore_neutralcol'		=> 'Profile: Neutral reputation color',
'themesetting_remove_page_headers'		=> 'Remove page headers',
'themesetting_slider_5_buttons'		=> 'Slider Buttons',
'themesetting_social_links_pos'		=> 'Social Link Position<span id="themesettings_desc">You can add Social link by going to</span><span id="themesettings_desc">ACP > System > Settings > <strong>General Configuration</strong></span>',
'themesetting_cat_private_ti_r3'		=> 'Cover title (3)',
'themesetting_specific_cat_style'		=> 'Enable',
'themesetting_toggle_off'		=> 'Toggles: Off',
'themesetting_footer_crbackground'		=> 'Copyright Footer: Background',
'themesetting_footer_showonmobile'		=> 'Show on mobiles & tablets?',
'themesetting_sl_style'		=> 'Style',
'themesetting_slider_autoplay_delay'		=> 'Autoplay speed (In ms)',
'themesetting_slider_4'		=> 'Slider (4)',
'themesetting_selecttree_bg'		=> 'SelectTree: Background',
'themesetting_g_widget_content_top'		=> 'Content',
'themesetting_toggle_on'		=> 'Toggles: On',
'themesetting_cat_ti_bg_gradi_r1'		=> 'Category title gradients (1)<span id="themesettings_desc"> Some gradient websites<a href="http://www.colorzilla.com/gradient-editor/" target="_blank" id="themesettings_desc_a"> gradient-editor </a><a href="http://uigradients.com/" target="_blank" id="themesettings_desc_a"> uigradients </a></span>',
'themesetting_nt_toggle'		=> 'Enable',
'themesetting_g_widget_content_bottom'		=> 'Content',
'themesetting_messages_success'		=> 'Message background: Success',
'themesetting_nt_hidemobile'		=> 'Hide on mobile?',
'themesetting_g_widget_title_color'		=> 'Widget title Color',
'themesetting_slider_article_truncatetitle'		=> 'Truncate title?',
'themesetting_main_nav_uppercase'		=> 'Main Nav Bar: Uppercase text?',
'theme_custom_tab_topic_view'		=> 'Topic View',
'themesetting_flashmessage_bg'		=> 'Flash Message: Background',
'themesetting_category_r1'		=> 'Style forum categories (1)',
'themesetting_sl_customizecolor'		=> 'Use custom colors',
'theme_custom_tab_colorizer'		=> 'Palette',
'themesetting_topic_avatar_dimensions'		=> 'Avatar dimensions',
'themesetting_ipsquotecode_bg'		=> 'Quote/Code background',
'themesetting_header_image'		=> 'Header image',
'themesetting_main_nav_bottomborder'		=> 'Main Nav Bar: Bottom border',
'themesetting_footer_articles'		=> 'Pages Articles',
'theme_custom_tab_global_widgets'		=> 'Custom Widgets',
'themesetting_cat_ti_bg_r1'		=> 'Category title background (1)',
'themesetting_slider_3_img'		=> 'Slider Image',
'themesetting_nt_custom_content'		=> 'Custom tickers<span id="themesettings_desc">Ticker must be in an <strong>li</strong> tag</span>',
'themesetting_item_status_notactive'		=> 'Item Status Badges NOT Active',
'themesetting_dataitem_info'		=> 'Data item background: Info',
'themesetting_pagination_tabbg'		=> 'Pagination: Background',
'themesetting_cat_ti_font_r2'		=> 'Category title color (2)',
'themesetting_headerimage'		=> 'Header image<span id="themesettings_desc">This image is used on pages when there is no slider</span>',
'themesetting_notification_readbg'		=> 'Notification: Status background',
'themesetting_slider_article_truncatecontent'		=> 'Truncate content (in lines)',
'themesetting_messages_error'		=> 'Message background: Error',
'themesetting_slider_2_buttons'		=> 'Slider Buttons',
'themesetting_ipsdialog_title'		=> 'Pop-up: Title',
'themesetting_tabs_fontcolor'		=> 'Tabs: button text',
'theme_custom_tab_sidebars_widgets'		=> 'Widgets & Titles',
'themesetting_nav_fontcustom'		=> 'Navigation Font<span id="themesettings_desc">Type a<a href="https://fonts.google.com/" target="_blank" id="themesettings_desc_a">google fonts</a>name</span>',
'theme_custom_tab_categories_sidebars'		=> 'Style forums',
'themesetting_slider_4_img'		=> 'Slider Image',
'themesetting_cat_private_bg_r3'		=> 'Cover background (3)<span id="themesettings_desc">%70 Transparent</span>',
'themesetting_cat_ti_bg_gradi_r2'		=> 'Category title gradients (2)<span id="themesettings_desc">Some gradient websites<a href="http://www.colorzilla.com/gradient-editor/" target="_blank" id="themesettings_desc_a"> gradient-editor </a><a href="http://uigradients.com/" target="_blank" id="themesettings_desc_a"> uigradients </a></span>',
'themesetting_g_widget_position_bottom'		=> 'Where to show?',
'themesetting_cat_ti_font_r3'		=> 'Category title color (3)',
'themesetting_slider_enable_articles'		=> 'Pages Articles',
'theme_custom_tab_social_links'		=> 'Social Links',
'theme_custom_tab_bodytab'		=> 'Body',
'themesetting_slider_5_wcs'		=> 'Who can see?',
'themesetting_sl_iconcolor'		=> 'Icon color',
'themesetting_slider_4_content'		=> 'Content',
'themesetting_nt_title'		=> 'Title',
'themesetting_site_titlefont'		=> 'Header logo: Text Color',
'themesetting_notification_unreadfont'		=> 'Notification: New status font',
'themesetting_topic_author_panel_y'		=> 'Author panel background gradient',
'themesetting_u_hdrimgs'		=> 'Header image: Use from sliders',
'themesetting_site_titlebg'		=> 'Header logo: Background',
'themesetting_slider_content_color'		=> 'Content Font Color',
'themesetting_selecttree_font'		=> 'SelectTree: Font',
'themesetting_dataitem_error'		=> 'Data item background: Error',
'themesetting_repscore_neutralbg'		=> 'Profile: Neutral reputation background',
'themesetting_editor_toolbartabson'		=> 'Editor Toolbar Active tabs',
'themesetting_messages_info'		=> 'Message background: Info',
'themesetting_entmt_snowfall'		=> 'Snowfall<span id="themesettings_desc">Let it Snow!</span>',
'themesetting_entmt_xmasmode'		=> 'Christmas mode',
'themesetting_cat_private_r1'		=> 'Apply a cover (1)',
'themesetting_colorizermain'		=> 'Palette',
'themesetting_g_widget_title_bg'		=> 'Widget title background',
'themesetting_ipsmenu_title_bg'		=> 'ipsMenu Title Background',
'theme_custom_tab_entertainment'		=> 'Entertainment',
);
