<ips:template parameters="$indexData, $itemData, $url, $condensed" />
{{if $condensed}}
	{{if $itemData['record_image']}}
		<span class='ipsThumb_bg ipsThumb_small ipsPos_left' style='background-image: url("{file="$itemData['record_image']" extension="cms_Records"}")'>
			<img src='{file="$itemData['record_image']" extension="cms_Records"}' alt='{$indexData['index_title']}' class="">
		</span>
	{{endif}}
{{else}}
	<div class='ipsColumns ipsColumns_collapsePhone'>
		{{if $itemData['record_image']}}
			<div class='ipsColumn ipsColumn_medium'>
				<a href='{$url}'>
						{template="thumbImage" group="global" app="core" location="front" params="$itemData['record_image'], $indexData['index_title'], 'large', '', 'view_this', NULL, 'cms_Records'"}
				</a>
			</div>
		{{endif}}
		<div class='ipsColumn ipsColumn_fluid {{if $itemData['record_image']}}ipsStream_snippetInfo{{endif}}'>
			{{if trim( $indexData['index_content'] ) !== ''}}
				<div class='ipsSpacer_top ipsSpacer_half ipsType_richText ipsType_break ipsType_medium' {{if !( \IPS\Dispatcher::i()->application->directory == 'core' and \IPS\Dispatcher::i()->module and \IPS\Dispatcher::i()->module->key == 'search' )}}data-ipsTruncate data-ipsTruncate-type='remove' data-ipsTruncate-size='2 lines' data-ipsTruncate-watch='false'{{else}}data-searchable data-findTerm{{endif}}>
					{expression="\IPS\Content\Search\Result::preDisplay( $indexData['index_content'] )" raw="true"}
				</div>
			{{endif}}
		</div>
	</div>
{{endif}}